In [70]:
d={"2015-01-13":"7.31","2015-01-14":"7.28","2015-01-15":"7.40","2015-01-16":"7.43","2015-01-17":"7.41"}

In [71]:
d

{'2015-01-13': '7.31',
 '2015-01-14': '7.28',
 '2015-01-15': '7.40',
 '2015-01-16': '7.43',
 '2015-01-17': '7.41'}

In [72]:
d['2015-01-20']=7.44

In [73]:
d

{'2015-01-13': '7.31',
 '2015-01-14': '7.28',
 '2015-01-15': '7.40',
 '2015-01-16': '7.43',
 '2015-01-17': '7.41',
 '2015-01-20': 7.44}

In [74]:
price=[]

In [75]:
import time

In [76]:
time.ctime()

'Mon Feb  3 07:08:52 2020'

In [77]:
from datetime import datetime

In [78]:
datetime.now()

datetime.datetime(2020, 2, 3, 7, 8, 52, 538950)

In [79]:
from datetime import date

In [80]:
curdate=date.fromisoformat('2015-01-21')

In [81]:
curdate

datetime.date(2015, 1, 21)

In [82]:
for key in d.keys():
    if curdate.day - date.fromisoformat(key).day <= 4:
        price.append(d[key])
    else:
        continue

In [83]:
price

['7.41', 7.44]

In [84]:
d['2015-01-16']='7.50'

In [85]:
d

{'2015-01-13': '7.31',
 '2015-01-14': '7.28',
 '2015-01-15': '7.40',
 '2015-01-16': '7.50',
 '2015-01-17': '7.41',
 '2015-01-20': 7.44}

In [86]:
import numpy as np

In [87]:
array1=np.array(range(6))

In [88]:
array1

array([0, 1, 2, 3, 4, 5])

In [89]:
array1.shape

(6,)

In [90]:
array1.shape=2,3

In [91]:
array1

array([[0, 1, 2],
       [3, 4, 5]])

In [92]:
print(array1)

[[0 1 2]
 [3 4 5]]


In [93]:
array2=array1.reshape(3,2)

In [94]:
array2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [95]:
array1[1,2]=88

In [96]:
print(array1)

[[ 0  1  2]
 [ 3  4 88]]


In [97]:
print(array2)

[[ 0  1]
 [ 2  3]
 [ 4 88]]


In [98]:
array3=np.array([[1,2,3],[5,6,7],[7,8,9]])

In [99]:
print(array3)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


In [100]:
array3.shape

(3, 3)

In [101]:
array4=np.arange(13,1,-1)

In [102]:
print(array4)

[13 12 11 10  9  8  7  6  5  4  3  2]


In [103]:
array5=array4.reshape(3,2,2)

In [104]:
array5

array([[[13, 12],
        [11, 10]],

       [[ 9,  8],
        [ 7,  6]],

       [[ 5,  4],
        [ 3,  2]]])